baseURL = "https://abouletonfilm.com/"
languageCode = "fr-FR"
title = "Aboule ton film"
DefaultContentLanguage = "fr"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]
paginate = 100
publishDir = "(root)/../../misc1_out"
